### ISSUE TITLE
Script error when disabled

### ISSUE THREAD

**Issue by Aptronymist** [Filexor/Clip_IO#11]
I'm using Vlad's fork, but this error has started popping up in my log today, with clip input not enabled, and clip output having everything unchecked.

15:06:48-567089 ERROR    Running script process batch: H:\AI\SD.Next\extensions\Clip_IO\scripts\Clip_IO.py:
                         AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\AI\SD.Next\modules\scripts.py:430 in process_batch                                                               │
│                                                                                                                     │
│   429 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                      │
│ > 430 │   │   │   │   script.process_batch(p, *args, **kwargs)                                                      │
│   431 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                     │
│                                                                                                                     │
│ H:\AI\SD.Next\extensions\Clip_IO\scripts\Clip_IO.py:614 in process_batch                                            │
│                                                                                                                     │
│    613 │   │   Clip_IO.mode_negative = args[2]                                                                      │
│ >  614 │   │   Clip_IO.evacuate_get_conds_with_caching = p.get_conds_with_caching                                   │
│    615 │   │   p.get_conds_with_caching = Clip_IO.get_my_get_conds_with_caching(p)                                  │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'get_conds_with_caching'

**Comment by Filexor** [comment]
I found vladmandic/automatic is way behind from AUTOMATIC1111/stable-diffusion-webui .
I updated the code and if you get Clip I/O related error other than warning that says "Your web ui is too old to access p: processing.StableDiffusionProcessing .", let me know.

**Comment by Aptronymist** [comment]
> I found vladmandic/automatic is way behind from AUTOMATIC1111/stable-diffusion-webui . I updated the code and if you get Clip I/O related error other than warning that says "Your web ui is too old to access p: processing.StableDiffusionProcessing .", let me know.

I understand, but it's not "way behind", it's largely rewritten and less buggy because Vlad is professional about his work.
You should try it and see, as sd-webui is still playing catchup on some features sd.next has had for a month or more.
[Some of his guidelines on extension behavior](https://github.com/vladmandic/automatic/wiki/Extensions) for example, whereas there are none for auto1111 and it's a wild west of misbehaving code.

I look forward to exploring your extension, thank you!

**Comment by Aptronymist** [comment]
I can confirm that the error is no longer happening without it on, so I'll close this, thank you again.
